version: '3.8'

services:
  app:
    image: nextjs-dev
    build: .
    ports:
      - 3000:3000
    volumes:
      - ./app:/app/app
      - ./components:/app/components
      - ./lib:/app/lib
      - ./public:/app/public
      - ./styles:/app/styles
