import ScrollToTop from '@/components/data-input/ScrollToTop'
import AppHeader from '@/components/global/AppHeader'
import Providers from '@/lib/providers'
import { poppins } from '@/styles/fonts'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <Providers>
          <main>
            <AppHeader />
            {children}
            <ScrollToTop />
          </main>
        </Providers>
      </body>
    </html>
  )
}
